theme: "jekyll-theme-minimal"
title: Cory Glover
description: PhD Candidate in Network Science at Northeastern University under Dr. Albert-László Barabási.

sidebar:
  image: "/assets/images/Cory.jpeg"
  about_title: "About Me"
  about_text: "Hi, I'm Cory Glover, a scientist passionate about solving problems with math."

