remote_theme: "jekyll/minima@1e8a445"
title: Cory Glover
description: A scientist who loves to be the ''math guy'' across a wide range of problems. PhD Candidate in Network Science at Northeastern University under Dr. Albert-László Barabási.

