theme: "jekyll-theme-minimal"
title: Cory Glover
description: PhD Candidate in Network Science at Northeastern University under Dr. Albert-László Barabási.
image: <img src="pictures/Cory.jpeg" alt="Your Image" style="width: 25%; margin-right: 20px;">